### ISSUE TITLE
ruby/new_safe_navigation_operator sometimes ignores the closing round bracket of try

### ISSUE THREAD

**Issue by mkoentopf** [xinminlabs/synvert-snippets-ruby#229]
This expression will be converted wrong
```ruby
linkt_to(profile.try(:link), class: "thumbnails")
```
to
```ruby
linkt_to(profile&.linkclass: "thumbnails")
#               WRONG ^
```
if you use the ruby/new_safe_navigation_operator snippet

**Comment by flyerhzm** [comment]
@mkoentopf I have fixed it, you need to 

1. update synvert-core to 1.3.1, `gem install -g synvert-core`
2. sync synvert snippets, `synvert-ruby --sync`
3. then run the snippet, `synvert-ruby -r ruby/new_safe_navigation_operator <project-path>`

**Comment by mkoentopf** [comment]
@flyerhzm Awesome.
The `ruby/new_safe_navigation_operator` snippet is now working perfectly.
Thank you very much.
